export const vehicles = [
  {
    id: "2Auto",
    image: "/img/vehicles/Auto/2AxlesAuto.png",
    type: "Auto",
    subtype: "Auto",
    axles: 2,
    description: "Car, SUV or Pickup truck",
  },
  {
    id: "3Auto",
    image: "/img/vehicles/Auto/3AxlesAuto.png",
    type: "Auto",
    subtype: "Auto",
    axles: 3,
    description: "Car, SUV or Pickup truck towing 1-axle trailer",
  },
  {
    id: "4Auto",
    image: "/img/vehicles/Auto/4AxlesAuto.png",
    type: "Auto",
    subtype: "Auto",
    axles: 4,
    description: "Car, SUV or Pickup truck towing 2-axle trailer",
  },
  {
    id: "2DualTire",
    image: "/img/vehicles/Auto/2AxlesDualTire.png",
    type: "Auto",
    subtype: "DualTire",
    axles: 2,
    description: "SUV or Pickup, 4 tires on rear",
  },
  {
    id: "3DualTire",
    image: "/img/vehicles/Auto/3AxlesDualTire.png",
    type: "Auto",
    subtype: "DualTire",
    axles: 3,
    description: "SUV or Pickup, 4 tires on rear, 1-axle trailer",
  },
  {
    id: "4DualTire",
    image: "/img/vehicles/Auto/4AxlesDualTire.png",
    type: "Auto",
    subtype: "DualTire",
    axles: 4,
    description: "SUV or Pickup, 4 tires on rear, 2-axle trailer",
  },
  {
    id: "2EV",
    image: "/img/vehicles/EV/2AxlesEV.png",
    type: "EV",
    subtype: "EV",
    axles: 2,
    description: "EV",
  },
  {
    id: "3EV",
    image: "/img/vehicles/EV/3AxlesEV.png",
    type: "EV",
    subtype: "EV",
    axles: 3,
    description: "EV towing 1-axle trailer",
  },
  {
    id: "4EV",
    image: "/img/vehicles/EV/4AxlesEV.png",
    type: "EV",
    subtype: "EV",
    axles: 4,
    description: "EV towing 2-axle trailer",
  },
  {
    id: "2Truck",
    image: "/img/vehicles/Truck/2AxlesTruck.png",
    type: "Truck",
    subtype: "Truck",
    axles: 2,
    description: "Truck - 2 Axles",
  },
  {
    id: "3Truck",
    image: "/img/vehicles/Truck/3AxlesTruck.png",
    type: "Truck",
    subtype: "Truck",
    axles: 3,
    description: "Truck - 3 Axles",
  },
  {
    id: "4Truck",
    image: "/img/vehicles/Truck/4AxlesTruck.png",
    type: "Truck",
    subtype: "Truck",
    axles: 4,
    description: "Truck - 4 Axles",
  },
  {
    id: "5Truck",
    image: "/img/vehicles/Truck/5AxlesTruck.png",
    type: "Truck",
    subtype: "Truck",
    axles: 5,
    description: "Truck - 5 Axles",
  },
  {
    id: "6Truck",
    image: "/img/vehicles/Truck/6AxlesTruck.png",
    type: "Truck",
    subtype: "Truck",
    axles: 6,
    description: "Truck - 6 Axles",
  },
  {
    id: "7Truck",
    image: "/img/vehicles/Truck/7AxlesTruck.png",
    type: "Truck",
    subtype: "Truck",
    axles: 7,
    description: "Truck - 7 Axles",
  },
  {
    id: "8Truck",
    image: "/img/vehicles/Truck/8AxlesTruck.png",
    type: "Truck",
    subtype: "Truck",
    axles: 8,
    description: "Truck - 8 Axles",
  },
  {
    id: "9Truck",
    image: "/img/vehicles/Truck/9AxlesTruck.png",
    type: "Truck",
    subtype: "Truck",
    axles: 9,
    description: "Truck - 9 Axles",
  },
  {
    id: "2Bus",
    image: "/img/vehicles/Bus/2AxlesBus.png",
    type: "Bus",
    subtype: "Bus",
    axles: 2,
    description: "Bus - 2 Axles",
  },
  {
    id: "3Bus",
    image: "/img/vehicles/Bus/3AxlesBus.png",
    type: "Bus",
    subtype: "Bus",
    axles: 3,
    description: "Bus - 3 Axles",
  },
  {
    id: "2Motorcycle",
    image: "/img/vehicles/Motorcycle/2AxlesMotorcycle.png",
    type: "Motorcycle",
    subtype: "Motorcycle",
    axles: 2,
    description: "Motorcycle",
  },
  {
    id: "3Motorcycle",
    image: "/img/vehicles/Motorcycle/3AxlesMotorcycle.png",
    type: "Motorcycle",
    subtype: "Motorcycle",
    axles: 3,
    description: "Motorcycle towing trailer",
  },
  {
    id: "2Rv",
    image: "/img/vehicles/Rv/2AxlesRv.png",
    type: "Rv",
    subtype: "Rv",
    axles: 2,
    description: "RV",
  },
  {
    id: "3Rv",
    image: "/img/vehicles/Rv/3AxlesRv.png",
    type: "Rv",
    subtype: "Rv",
    axles: 3,
    description: "RV towing 1-axle trailer",
  },
  {
    id: "4Rv",
    image: "/img/vehicles/Rv/4AxlesRv.png",
    type: "Rv",
    subtype: "Rv",
    axles: 4,
    description: "RV towing 2-axle trailer",
  },
  {
    id: "2TNC",
    image: "/img/vehicles/TNC/2AxlesTNC.png",
    type: "TNC",
    subtype: "TNC",
    axles: 2,
    description: "Rideshare - Car, SUV or Pickup truck",
  },
  {
    id: "2TNCPool",
    image: "/img/vehicles/TNC/2AxlesTNCPool.png",
    type: "TNC",
    subtype: "TNCPool",
    axles: 2,
    description: "Rideshare Pool - Car, SUV or Pickup truck",
  },
  {
    id: "2Taxi",
    image: "/img/vehicles/TNC/2AxlesTaxi.png",
    type: "TNC",
    subtype: "Taxi",
    axles: 2,
    description: "Taxi - Car, SUV or Pickup truck",
  },
  {
    id: "2TaxiPool",
    image: "/img/vehicles/TNC/2AxlesTaxiPool.png",
    type: "TNC",
    subtype: "TaxiPool",
    axles: 2,
    description: "Taxi Pool - Car, SUV or Pickup truck",
  },
  {
    id: "2Carpool2",
    image: "/img/vehicles/TNC/Carpool2.png",
    type: "TNC",
    subtype: "Carpool2",
    axles: 2,
    description: "Carpool (2 occupants)",
  },
  {
    id: "2Carpool3",
    image: "/img/vehicles/TNC/Carpool3.png",
    type: "TNC",
    subtype: "Carpool3",
    axles: 2,
    description: "Carpool (3+ occupants)",
  },
];

export const types = [
  {
    type: "Auto", // first Option in the select vehicle type
    description: "Car, SUV, Pickup truck",
  },
  {
    type: "EV", // first Option in the select vehicle type
    description: "Electric vehicle",
  },
  {
    type: "Truck", // first Option in the select vehicle type
    description: "Truck",
  },
  {
    type: "Bus", // first Option in the select vehicle type
    description: "Bus",
  },
  {
    type: "Motorcycle", // first Option in the select vehicle type
    description: "Motorcycle",
  },
  {
    type: "Rv", // first Option in the select vehicle type
    description: "Recreational vehicle",
  },
  {
    type: "TNC", // first Option in the select vehicle type
    description: "Rideshare, Taxi, Carpool",
  },
];
